AWSTemplateFormatVersion: '2010-09-09'
Description: 'Neo-Terminal Portfolio Infrastructure - S3, CloudFront, Route53'

Parameters:
  DomainName:
    Type: String
    Description: Your custom domain name (e.g., portfolio.dev)
    Default: portfolio.dev
  
  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID for your domain
    Default: ''

Resources:
  # S3 Bucket for static website hosting
  PortfolioS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${DomainName}-portfolio'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
      Tags:
        - Key: Project
          Value: Neo-Terminal-Portfolio

  # S3 Bucket Policy
  PortfolioS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PortfolioS3Bucket
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub '${PortfolioS3Bucket.Arn}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${PortfolioCloudFrontDistribution}'

  # CloudFront Origin Access Control
  PortfolioOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${DomainName}-oac'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # ACM Certificate (must be in us-east-1 for CloudFront)
  PortfolioCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub 'www.${DomainName}'
      ValidationMethod: DNS
      Tags:
        - Key: Project
          Value: Neo-Terminal-Portfolio

  # CloudFront Distribution
  PortfolioCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2and3
        DefaultRootObject: index.html
        Aliases:
          - !Ref DomainName
          - !Sub 'www.${DomainName}'
        ViewerCertificate:
          AcmCertificateArn: !Ref PortfolioCertificate
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt PortfolioS3Bucket.RegionalDomainName
            OriginAccessControlId: !GetAtt PortfolioOAC.Id
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # Managed-CachingOptimized
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf # Managed-CORS-S3Origin
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 404
            ResponsePagePath: /404.html
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /404.html
        PriceClass: PriceClass_100
        Tags:
          - Key: Project
            Value: Neo-Terminal-Portfolio

  # Route53 Record for root domain
  PortfolioRoute53RecordRoot:
    Type: AWS::Route53::RecordSet
    Condition: HasHostedZone
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront hosted zone ID
        DNSName: !GetAtt PortfolioCloudFrontDistribution.DomainName

  # Route53 Record for www subdomain
  PortfolioRoute53RecordWWW:
    Type: AWS::Route53::RecordSet
    Condition: HasHostedZone
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub 'www.${DomainName}'
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt PortfolioCloudFrontDistribution.DomainName

Conditions:
  HasHostedZone: !Not [!Equals [!Ref HostedZoneId, '']]

Outputs:
  S3BucketName:
    Description: S3 Bucket Name
    Value: !Ref PortfolioS3Bucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'

  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref PortfolioCloudFrontDistribution
    Export:
      Name: !Sub '${AWS::StackName}-DistributionId'

  CloudFrontDomainName:
    Description: CloudFront Domain Name
    Value: !GetAtt PortfolioCloudFrontDistribution.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDomain'

  WebsiteURL:
    Description: Portfolio Website URL
    Value: !Sub 'https://${DomainName}'
